#!/bin/bash

export POSIXLY_CORRECT=yes

print_help(){
    echo "Mole program"
    echo 
    echo "sposoby pouzita:"
    echo "mole -h"
    echo "mole [-g GROUP] FILE"
    echo "mole [-m] [FILTERS] [DIRECTORY]"
    echo "mole list [FILTERS] [DIRECTORY]"
    echo "mole secret-log [-b DATE] [-a DATE] [DIRECTORY1 [DIRECTORY2 [...]]]"
}

choose_editor(){
    if [ -z "${EDITOR}" ]; then
        if [ -z "${VISUAL}" ]; then
            EDITOR=vi
        else 
            EDITOR=${VISUAL}
        fi
    fi
}

dir_check(){
    if [ -z "${DIRECTORY}" ]; then
        DIRECTORY=$(pwd)
    fi
    if [ ! -d "${DIRECTORY}" ]; then
        echo "Directory does not exists"
        exit 1
    fi
}

last_opened(){
    REALPATH= awk -F";" -v dir="$DIRECTORY" -v path="" '{if($3=="DIRECTORY")path=$2;}END{print path}' ${MOLE_RC}
}

EDITOR=nano
VISUAL=
GROUP="-"
DIRECTORY=$(pwd)
DATE=$(date +%Y-%m-%d)
TIME=$(date +%H-%M)

while [ "$#" -gt 0 ]; do
    case $1 in
    "-h") print_help
    exit 0
    ;;
    "-g")
    GROUP=$2
    shift
    shift
    ;;
    "-m")
    DIRECTORY=$2
    dir_check
    last_opened
    echo "$REALPATH"
    shift
    shift
    FILE="ahojku"
    ;;
    "list")
    DIRECTORY=$2
    shift
    FILE=$1
    echo $DIRECTORY
    echo
    list
    exit 0
    ;;
    esac
    break
done

FILE=$1
REALPATH=$(realpath "$FILE")
echo ${GROUP}";"${REALPATH}";"${DIRECTORY}";"${FILE}";"${DATE}"_"${TIME}>> ${MOLE_RC}

choose_editor
eval $EDITOR $REALPATH
echo ${GROUP}";"${REALPATH}";"${DIRECTORY}";"${FILE}";"${DATE}"_"${TIME}>> ${MOLE_RC}"